### ISSUE TITLE
viroBlast -Your job is being processed

### ISSUE THREAD

**Issue by ling-t** [MullinsLab/ViroblastStandalone#1]
I have an issue in running viroBlast from my localhost. It is stand-alone BLAST web server that can be installed in your localhost. When I run it from the above link, the result comes in less than one minutes. But when I run it from my localhost "after install it", it takes "days" showing:

Your job is being processed
Your job id is .......
Please wait here to watch the progress of your job.
This page will update itself automatically until search is done.

**Comment by wdenggithub** [comment]
Hi, thanks for your message. Could you please provide more details of the issue? in your local viroblast folder, are there any files in data/, which files in there, is there error messages in error file, the permission of data/, etc.? 

Best,

Wenjie Deng

**Comment by ling-t** [comment]
Thanks for your answer, I have solved my problem and Viroblast works well.
Best,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MullinsLab/ViroblastStandalone"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月9日(星期六) 凌晨2:55
收件人:&nbsp;"MullinsLab/ViroblastStandalone"<ViroblastStandalone@noreply.github.com&gt;;
抄送:&nbsp;"1342219952"<1342219952@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MullinsLab/ViroblastStandalone] viroBlast -Your job is being processed (#1)





 
Hi, thanks for your message. Could you please provide more details of the issue? in your local viroblast folder, are there any files in data/, which files in there, is there error messages in error file, the permission of data/, etc.?
 
Best,
 
Wenjie Deng

**Comment by wdenggithub** [comment]
Great! Please let us know if you have further questions.

Cheers,

Wenjie
